backend/controllers/LabellistController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Bsproductlist1;
use common\models\search\Bsproductlist1Search;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * LabellistController implements the CRUD actions for Bsproductlist1 model.
 */
class LabellistController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Bsproductlist1 models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new Bsproductlist1Search();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Bsproductlist1 model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Перегляд  :" . $model->productname,
                'content' => $this->renderAjax('view', [
                    'model' => $this->findModel($id),
                ]),
                'footer' => Html::button('Закрити', ['class' => 'btn btn-primary pull-left', 'data-dismiss' => "modal"]) .
                    Html::a('Змінити', ['update', 'id' => $id], ['class' => 'btn btn-warning', 'role' => 'modal-remote'])
            ];
        } else {
            return $this->render('view', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Creates a new Bsproductlist1 model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Bsproductlist1();

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Створити новий Bsproductlist1",
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрити', ['class' => 'btn btn-primary pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Зберегти', ['class' => 'btn btn-info', 'type' => "submit"])

                ];
            } else if ($model->load($request->post()) && $model->save()) {
                return [
                    'forceReload' => '#crud-datatable-pjax',
                    'title' => "Створити новий Bsproductlist1",
                    'content' => '<span class="text-success">Create Bsproductlist1 success</span>',
                    'footer' => Html::button('Закрити', ['class' => 'btn btn-primary pull-left', 'data-dismiss' => "modal"]) .
                        Html::a('Створити ще', ['create'], ['class' => 'btn btn-info', 'role' => 'modal-remote'])

                ];
            } else {
                return [
                    'title' => "Створити новий Bsproductlist1",
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрити', ['class' => 'btn btn-primary pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Зберегти', ['class' => 'btn btn-info', 'type' => "submit"])

                ];
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }

    /**
     * Updates an existing Bsproductlist1 model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Змінити: " . $model->productname,
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрити', ['class' => 'btn btn-primary pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Зберегти', ['class' => 'btn btn-info', 'type' => "submit"])
                ];
            } else if ($model->load($request->post()) && $model->save()) {
                return [
                    'forceReload' => '#crud-datatable-pjax',
                    'title' => $model->productname,
                    'content' => $this->renderAjax('view', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрити', ['class' => 'btn btn-primary pull-left', 'data-dismiss' => "modal"]) .
                        Html::a('Змінити', ['update', 'id' => $id], ['class' => 'btn btn-warning', 'role' => 'modal-remote'])
                ];
            } else {
                return [
                    'title' => "Змінити: " . $model->productname,
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрити', ['class' => 'btn btn-primary pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Зберегти', ['class' => 'btn btn-info', 'type' => "submit"])
                ];
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing Bsproductlist1 model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $label = $this->findModel($id);
        if ($label->used == 1) {
            $label->used = 0;
        } else {
            $label->used = 1;
        }
        $label->save();
        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
        } else {
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

    /**
     * Delete multiple existing Bsproductlist1 model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBulkDelete()
    {
        $request = Yii::$app->request;
        $pks = explode(',', $request->post('pks')); // Array or selected records primary keys
        foreach ($pks as $pk) {
            $label = $this->findModel($pk);
            if ($label->used == 1) {
                $label->used = 0;
            } else {
                $label->used = 1;
            }
            $label->save();;
        }

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
        } else {
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }

    }

    public function actionLabel1($id)
    {
        $model = $this->findModel($id);
        return $this->render('label', [
            'picture' => $model->pic1,
        ]);
    }

    public function actionLabel2($id)
    {
        $model = $this->findModel($id);
        return $this->render('label', [
            'picture' => $model->pic2,
        ]);
    }

    /**
     * Finds the Bsproductlist1 model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Bsproductlist1 the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Bsproductlist1::findOne($id)) !== null) {
            return $model;

backend/views/labellist/_columns.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'productname',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'producttype',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'barscale1',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'barscale2',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'term1',
    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'term2',
    // ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'countg',
    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'mtara',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'usush',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'used',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'minmassa',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'maxmassa',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'code1C',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'country_id',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'param1',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'param2',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'param3',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'param4',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'param5',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'param6',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'et1',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'et2',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'pic1',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'pic2',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign' => 'middle',
        'urlCreator' => function ($action, $model, $key, $index) {
            return Url::to([$action, 'id' => $key]);
        },
        'width' => '120px',
        'template' => '{view} {update} {delete} {label1} {label2}',
        'buttons' => [
            'label1' => function ($model, $key, $index) {
                return Html::a(
                    '<button class="btn btn-success btn-xs"><span class="glyphicon glyphicon-picture"></span></button>',
                    Url::to(['labellist/label1', 'id' => $key->id])
                );
            },
            'label2' => function ($model, $key, $index) {
                return Html::a(
                    '<button class="btn btn-success btn-xs"><span class="glyphicon glyphicon-picture"></span></button>',
                    Url::to(['labellist/label2', 'id' => $key->id])
                );
            }
        ],
        'viewOptions' => ['label' => '<button class="btn btn-info btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button>', 'role' => 'modal-remote'],
        'updateOptions' => ['label' => '<button class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>', 'role' => 'modal-remote', 'title' => 'Изменить', 'data-toggle' => 'tooltip'],
        'deleteOptions' => ['role' => 'modal-remote', 'title' => 'Удалить',
            'data-confirm' => false, 'data-method' => false,// for overide yii data api
            'data-request-method' => 'post',
            'label' => '<button class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></button>',
            'data-toggle' => 'tooltip',
            'data-confirm-title' => 'Вы уверенны?',
            'data-confirm-message' => 'Вы действительно хотите удалить запись'],
    ],

];   

backend/views/labellist/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use common\models\Bscountry;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model common\models\Bsproductlist1 */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="bsproductlist1-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class='row'>
        <div class='col-lg-6'>
            <?= $form->field($model, 'country_id')->widget(Select2::classname(), [
                'name' => 'country_id',
                'value' => $model->country_id,
                'data' => Bscountry::getCountryList(),
                'hideSearch' => true,
                'pluginOptions' => [
                    'escapeMarkup' => new JsExpression("function(m) { return m; }"),
                    'allowClear' => true
                ]
            ]) ?>
        </div>
    </div>
    <div class='row'>
        <div class='col-lg-6'>
            <?= $form->field($model, 'productname')->textInput(['maxlength' => true]) ?>
        </div>
        <div class='col-lg-6'>
            <?= $form->field($model, 'producttype')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class='row'>
        <div class='col-lg-5'>
            <?= $form->field($model, 'barscale1')->textInput(['maxlength' => true]) ?>
        </div>
        <div class='col-lg-5'>
            <?= $form->field($model, 'barscale2')->textInput(['maxlength' => true]) ?>
        </div>
        <div class='col-lg-2'>
            <?= $form->field($model, 'code1C')->textInput() ?>
        </div>

    </div>
    <div class='row'>
        <div class='col-lg-3'>
            <?= $form->field($model, 'term1')->textInput() ?>
        </div>
        <div class='col-lg-3'>
            <?= $form->field($model, 'term2')->textInput() ?>
        </div>
        <div class='col-lg-3'>
            <?= $form->field($model, 'countg')->textInput() ?>
        </div>
        <div class='col-lg-3'>
            <?= $form->field($model, 'mtara')->textInput() ?>
        </div>
    </div>
    <div class='row'>
        <div class='col-lg-3'>
            <?= $form->field($model, 'usush')->textInput() ?>
        </div>
        <div class='col-lg-3'>
            <?= $form->field($model, 'minmassa')->textInput() ?>
        </div>
        <div class='col-lg-3'>
            <?= $form->field($model, 'maxmassa')->textInput() ?>
        </div>
        <div class='col-lg-3'>
            <?= $form->field($model, 'used')->checkbox() ?>
        </div>
    </div>
    <div class='row'>
        <?= $form->field($model, 'param1')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'param2')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'param3')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'param4')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'param5')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'param6')->textInput(['maxlength' => true]) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

backend/views/labellist/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Productlistsearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="productlist-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'category') ?>

    <div class="form-group">
        <?= Html::submitButton('Знайти', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Очистити', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/labellist/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Bsproductlist1 */

?>
<div class="bsproductlist1-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

backend/views/labellist/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\Bsproductlist1Search */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Bsproductlist1s';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<style>
    .modal-dialog {
        margin: 2px auto;
        z-index: 1100 !important;
    }
</style>
<div class="bsproductlist1-index">
    <div id="ajaxCrudDatatable">
        <?= GridView::widget([
            'id' => 'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax' => true,
            'rowOptions' => function ($model) {
                if ($model->used == 0) {
                    return ['style' => 'color:red'];
                }
            },
            'columns' => require(__DIR__ . '/_columns.php'),
            'toolbar' => [
                ['content' =>
                    '<div style="margin-top:10px;">' .
                    Html::a('Добавить <i class="glyphicon glyphicon-plus"></i>', ['create'],
                        ['role' => 'modal-remote', 'title' => 'Добавить', 'class' => 'btn btn-info']) .
                    '<ul class="panel-controls">
                        <li><a href="#" class="panel-fullscreen"><span class="fa fa-expand"></span></a></li>
                        <li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
                        <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                    </ul>  ' .
                    '</div>'
                ],
            ],
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
                'type' => 'warning',
                'heading' => '<i class="glyphicon glyphicon-list"></i> Bsproductlist1s listing',
                'before' => '',
                'after' => BulkButtonWidget::widget([
                        'buttons' => Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Знищити всі',
                            ["bulk-delete"],
                            [
                                "class" => "btn btn-danger btn-xs",
                                'role' => 'modal-remote-bulk',
                                'data-confirm' => false, 'data-method' => false,// for overide yii data api
                                'data-request-method' => 'post',
                                'data-confirm-title' => 'Ви впевненні?',
                                'data-confirm-message' => 'Ви дійсно хочете знищищити всі записи'
                            ]),
                    ]) .
                    '<div class="clearfix"></div>',
            ]
        ]) ?>
    </div>
</div>
<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "size" => Modal::SIZE_LARGE,
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>

backend/views/labellist/label.php
<?php

use common\models\Bscountry;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Bsproductlist1 */
?>
<style>
    .label-preview:hover {
        height: 900px;
    }
</style>
<div class="bsproductlist1-view">

    <?php
    echo '<img class="label-preview" src="data:image/jpeg;base64,' . base64_encode($picture) . '"/>';
    ?>

</div>

backend/views/labellist/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Bsproductlist1 */
?>
<div class="bsproductlist1-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/labellist/view.php
<?php

use common\models\Bscountry;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Bsproductlist1 */
?>
<div class="bsproductlist1-view">

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'productname',
            'producttype',
            'barscale1',
            'barscale2',
            'term1',
            'term2',
            'countg',
            'mtara',
            'usush',
            'used',
            'minmassa',
            'maxmassa',
            'code1C',
            [
                'attribute' => 'country_id',
                'format' => 'raw',
                'value' => function ($model) {
                    return Bscountry::getCountryList()[$model->country_id];
                }
            ],
            'param1',
            'param2',
            'param3',
            'param4',
            'param5',
            'param6',
        ],
    ]) ?>

</div>